### ISSUE TITLE
数据集如何制作

### ISSUE THREAD

**Issue by yasailiu** [LinkLiar/ZebraFish-MOT#1]
你好，数据集用什么软件制作的

**Comment by RoryLi98** [comment]
你给我留个联系方式吧，我来联系你

**Comment by yasailiu** [comment]
谢谢您能回我，我微信:15752521659。




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年07月03日 15:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LinkLiar/ZebraFish-MOT] 数据集如何制作 (Issue #1) |

你给我留个联系方式吧，我来联系你
